### ISSUE TITLE
acknowledgements

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/scipy_proceedings#1]
@shantenujha @iparask @mkhoshle is the following section ok? Otherwise, either push modifications or comment on this issue:

# Acknowledgements

MK and IP were supported by grant ACI-1443054 from the National Science Foundation.
SJ and OB were supported in part by grant ACI-1443054 from the National Science Foundation.
Computational resources were in part provided by the Extreme Science and Engineering Discovery Environment (XSEDE), which is supported by National Science Foundation grant number ACI-1053575 (allocation MCB130177 to OB and allocation TG-MCB090174 to JS).

**Comment by shantenujha** [comment]
JS --> SJ in "TG-MCB090174 to SJ"

otherwise fine. Thanks.

**Comment by mkhoshle** [comment]
I modified it.
