### ISSUE TITLE
explain goal in introduction

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/scipy_proceedings#10]
> If all DCD is doing is ripping bytes from disk without any processing then I wouldn't expect much dependence on parallelism at all. It should be entirely determined by the I/O bandwidth to the CPUs. 

That's exactly what the data show.

Maybe it is not clear that we would like to avoid any I/O cost and we would like to get our performance (reduced time to solution) by working on the compute problem in parallel. Make clearer in intro.

**Comment by mkhoshle** [comment]
Addressed!
