### ISSUE TITLE
check affiliations and acknowledgements

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/scipy_proceedings#22]
Hello authors ( @kain88-de @richardjgowers @iparask @mimischi ),

@VOD555 and I are trying to get a draft submitted by tomorrow (May 22). We are a bit late but judging from past scipy experience it should not be a problem to update the PR over the next few days. Apologies in advance for rushing you.

Please have a look at [papers/shujie_fan/pmda.rst](https://github.com/Becksteinlab/scipy_proceedings/blob/2019/papers/shujie_fan/pmda.rst) (or [paper.pdf](https://github.com/Becksteinlab/scipy_proceedings/files/3204702/paper.pdf)) and 

- check your name 
- affiliations
- email address (only in reST)
- acknowledgements

Any changes: make them on the reST (and submit a PR – you can just use the edit button on GitHub) or add the text below in the issue report.

Feel free to comment on anything else but as you can see, there's still a lot of work to be done.

## Affiliation

The affiliation should be the one at which you contributed to PMDA. You can have another one with "present address".
```reST
:author: A.U. Thor
:email: author@bilskirnir.ag
:institution: Asgard
:institution: present address: Avengers Group, Midgard 
```

## Acknowledgements
Add any funding acknowledgements or other acknowledgements. See what's already there and use something along the line "AUT was supported by a grant from the Department of Defense under contract AVG-SHIELDS-2019."

**Comment by orbeckst** [comment]
@richardjgowers , sorry, I had forgotten to ping you originally.

**Comment by iparask** [comment]
Thank you @orbeckst it is okay!

**Comment by mimischi** [comment]
All good from my side!

**Comment by orbeckst** [comment]
With PR #25 and #26 merged, everybody seems happy. Thank you all!
