### ISSUE TITLE
plot data as averages + stdev

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/scipy_proceedings#27]
The timing data should be *averages* for all runs where we have repeats.

- average
- error bar for 1 standard deviation

Note:
> For benchmark using distributed on local ssd and multiprocessing on Lustre, we only have single runs. For these using distributed on Lustre and multiprocessing on ssd, we have 5 runs for each case.

**Comment by VOD555** [comment]
All plots include averages and stdev now.
