### ISSUE TITLE
bigger font sizes in figures and make panels

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/scipy_proceedings#9]
*final* size not smaller than 7 points.

Make figs at final size (~2" x 2"), choose font size ~10pt.

- [ ] 3 + 4 (make panel 2 x 3)
- [ ] 5
- [ ] 6
- [ ] 7 + 8  (make panel 2x3)
- [ ] 9 (need to re-add numbers in Illustrator or Inkscape)
- [ ] 11
- [ ] 13
- [ ] 17: make a 3 / 2 (two row) single column plot
- [ ] MPI: make 19 an inset for Fig 18, add with Fig 20 into a two-row panel

Fig 10 and 12 are good examples. Fig 15 is borderline-ok.

**Comment by mkhoshle** [comment]
All the changes are addressed!
